# Use docker-based build environment (instead of openvz)
sudo: false
language: scala
scala:
- 2.11.6
jdk:
- oraclejdk7

cache:
  directories:
    - '$HOME/.ivy2/cache'

#branches:
#  only:
#  - master
notifications:
  email:
    recipients:
    - platform-engineering@digital.hmrc.gov.uk
#after_success:
#- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'